import { useState, useRef, useEffect } from "react";
import { Link, useLocation } from "wouter";
import { Home, Search, ListVideo, Users, Bell, MessageSquare, Dices, LogOut, ChevronDown, User } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { useGetNotifications, useGetRecommendationInbox, useGetMe } from "@workspace/api-client-react";
import { useLang, LANGS } from "@/lib/i18n";

export function Sidebar() {
  const [location] = useLocation();
  const { signOut } = useAuth();
  const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");
  const { t, lang, setLang } = useLang();
  const [langOpen, setLangOpen] = useState(false);
  const langRef = useRef<HTMLDivElement>(null);

  const { data: notifications } = useGetNotifications();
  const { data: recs } = useGetRecommendationInbox();
  const { data: myProfile } = useGetMe();

  const unreadNotifs = notifications?.filter(n => !n.read).length || 0;
  const unreadRecs = recs?.filter(r => !r.seen).length || 0;

  const isAutoGenerated = (s: string | null | undefined) =>
    !s || /^user_[a-z0-9]{6,10}$/i.test(s);
  const rawDisplay = myProfile?.displayName || myProfile?.username;
  const displayName = isAutoGenerated(rawDisplay) ? "" : (rawDisplay ?? "");
  const avatarUrl = myProfile?.avatarUrl || null;

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (langRef.current && !langRef.current.contains(e.target as Node)) {
        setLangOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  const navItems = [
    { icon: Home, label: t("home"), href: "/home" },
    { icon: Search, label: t("search"), href: "/search" },
    { icon: ListVideo, label: t("watchlists"), href: "/watchlists" },
    { icon: Dices, label: t("randomPick"), href: "/random-pick" },
    { icon: Users, label: t("friends"), href: "/friends" },
    {
      icon: MessageSquare,
      label: t("recommendations"),
      href: "/recommendations",
      badge: unreadRecs > 0 ? unreadRecs : 0,
    },
    {
      icon: Bell,
      label: t("notifications"),
      href: "/notifications",
      badge: unreadNotifs > 0 ? unreadNotifs : 0,
    },
  ];

  const currentLang = LANGS.find(l => l.code === lang) ?? LANGS[0];

  return (
    <div className="w-64 bg-[#050505] border-r border-[#1a1a1a] h-[100dvh] sticky top-0 flex flex-col hidden md:flex">
      {/* Logo + lang */}
      <div className="p-5 flex items-center justify-between border-b border-[#1a1a1a]">
        <div className="flex items-center gap-3">
          <img src={`${basePath}/logo.svg`} alt="CineClub" className="w-10 h-10" />
          <span className="font-bold text-xl tracking-tight bg-gradient-to-r from-amber-500 to-red-500 bg-clip-text text-transparent">CineClub</span>
        </div>

        {/* Language selector */}
        <div className="relative" ref={langRef}>
          <button
            onClick={() => setLangOpen(v => !v)}
            className="flex items-center gap-1.5 text-gray-400 hover:text-white transition-colors text-xs px-2 py-1.5 rounded-lg hover:bg-white/5 border border-transparent hover:border-gray-800"
            title={t("language")}
          >
            <img src={`https://flagcdn.com/20x15/${currentLang.countryCode}.png`} alt={currentLang.short} className="w-5 h-auto rounded-sm shrink-0" />
            <span className="font-medium">{currentLang.short}</span>
            <ChevronDown size={11} className="opacity-50" />
          </button>
          {langOpen && (
            <div className="absolute right-0 top-full mt-1 w-36 bg-[#111] border border-gray-800 rounded-xl shadow-2xl overflow-hidden z-50">
              {LANGS.map(l => (
                <button
                  key={l.code}
                  onClick={() => { setLang(l.code); setLangOpen(false); }}
                  className={`w-full flex items-center gap-2.5 px-3 py-2.5 text-sm transition-colors ${lang === l.code ? "bg-white/10 text-white" : "text-gray-400 hover:bg-white/5 hover:text-white"}`}
                >
                  <img src={`https://flagcdn.com/20x15/${l.countryCode}.png`} alt={l.short} className="w-5 h-auto rounded-sm shrink-0" />
                  <span className="font-medium">{l.short}</span>
                  <span className="text-gray-600 text-xs ml-auto">{l.label}</span>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Profile card — CineClub avatar + hoş geldin */}
      <Link href="/profile">
        <div className="mx-3 mt-3 p-3.5 rounded-xl bg-white/5 border border-white/5 hover:border-amber-500/30 hover:bg-white/[0.07] transition-all cursor-pointer group">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-full overflow-hidden bg-[#1a1a1a] border-2 border-white/10 group-hover:border-amber-500/40 transition-colors shrink-0">
              {avatarUrl ? (
                <img src={avatarUrl} alt={displayName || "Profil"} className="w-full h-full object-cover" />
              ) : (
                <div className="w-full h-full flex items-center justify-center">
                  <User size={18} className="text-gray-600 group-hover:text-gray-400 transition-colors" />
                </div>
              )}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-[11px] text-gray-600 leading-none mb-1">Hoş geldin,</p>
              <p className={`text-sm font-semibold truncate leading-tight ${displayName ? "bg-gradient-to-r from-amber-400 to-red-500 bg-clip-text text-transparent" : "text-gray-400"}`}>
                {displayName || "Profilim"}
              </p>
            </div>
          </div>
        </div>
      </Link>

      <nav className="flex-1 px-3 py-3 space-y-1">
        {navItems.map((item) => {
          const isActive = location === item.href || location.startsWith(`${item.href}/`);
          return (
            <Link key={item.href} href={item.href}>
              <div className={`flex items-center justify-between px-4 py-3 rounded-xl transition-all cursor-pointer ${
                isActive
                  ? "bg-white/10 text-white shadow-[inset_2px_0_0_0_#f59e0b]"
                  : "text-gray-400 hover:bg-white/5 hover:text-white"
              }`}>
                <div className="flex items-center gap-3">
                  <item.icon size={20} className={isActive ? "text-amber-500" : ""} />
                  <span className="font-medium">{item.label}</span>
                </div>
                {item.badge ? (
                  <span className="bg-amber-500 text-black text-xs font-bold px-2 py-0.5 rounded-full">
                    {item.badge}
                  </span>
                ) : null}
              </div>
            </Link>
          );
        })}
      </nav>

      <div className="p-3 border-t border-[#1a1a1a]">
        <button
          onClick={() => { signOut(); window.location.href = basePath || "/"; }}
          className="flex items-center gap-3 px-4 py-3 w-full rounded-xl text-gray-400 hover:bg-white/5 hover:text-red-400 transition-all"
        >
          <LogOut size={20} />
          <span className="font-medium">{t("logout")}</span>
        </button>
      </div>
    </div>
  );
}

export function MobileNav() {
  const [location] = useLocation();

  const navItems = [
    { icon: Home, href: "/home" },
    { icon: Search, href: "/search" },
    { icon: Dices, href: "/random-pick" },
    { icon: MessageSquare, href: "/recommendations" },
    { icon: Bell, href: "/notifications" },
  ];

  return (
    <div className="md:hidden fixed bottom-0 left-0 right-0 bg-[#050505]/90 backdrop-blur-md border-t border-[#1a1a1a] flex justify-around p-3 z-50">
      {navItems.map((item) => {
        const isActive = location === item.href || location.startsWith(`${item.href}/`);
        return (
          <Link key={item.href} href={item.href}>
            <div className={`p-2 rounded-xl transition-all ${isActive ? "text-amber-500" : "text-gray-400"}`}>
              <item.icon size={24} />
            </div>
          </Link>
        );
      })}
    </div>
  );
}
